### ISSUE TITLE
Class 'fpdi\FPDI' not found

### ISSUE THREAD

**Issue by ammarax** [Webklex/laravel-pdfmerger#10]
Class 'fpdi\FPDI' not found
on
Laravel Framework 5.8.35

Symfony\Component\Debug\Exception\FatalThrowableError thrown with message "Class 'fpdi\FPDI' not found"

i see that there is a pull request that will resolve the problem, please, merge it

Stacktrace:
#61 Symfony\Component\Debug\Exception\FatalThrowableError in /var/www/print.internionline.it/vendor/webklex/laravel-pdfmerger/src/PDFMerger/PDFMerger.php:62
#60 Webklex\PDFMerger\PDFMerger:__construct in /var/www/print.internionline.it/vendor/webklex/laravel-pdfmerger/src/PDFMerger/Providers/PDFMergerServiceProvider.php:39
#59 Webklex\PDFMerger\Providers\PDFMergerServiceProvider:Webklex\PDFMerger\Providers\{closure} in /var/www/print.internionline.it/vendor/laravel/framework/src/Illuminate/Container/Container.php:785
#58 Illuminate\Container\Container:build in /var/www/print.internionline.it/vendor/laravel/framework/src/Illuminate/Container/Container.php:667
#57 Illuminate\Container\Container:resolve in /var/www/print.internionline.it/vendor/laravel/framework/src/Illuminate/Container/Container.php:615
#56 Illuminate\Container\Container:make in /var/www/print.internionline.it/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:767
#55 Illuminate\Foundation\Application:make in /var/www/print.internionline.it/vendor/laravel/framework/src/Illuminate/Container/Container.php:1227
#54 Illuminate\Container\Container:offsetGet in /var/www/print.internionline.it/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php:176
#53 Illuminate\Support\Facades\Facade:resolveFacadeInstance in /var/www/print.internionline.it/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php:144
#52 Illuminate\Support\Facades\Facade:getFacadeRoot in /var/www/print.internionline.it/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php:233
#51 Illuminate\Support\Facades\Facade:__callStatic in /var/www/print.internionline.it/app/Http/Controllers/CommissioniController.php:26
#50 App\Http\Controllers\CommissioniController:export in /var/www/print.internionline.it/vendor/laravel/framework/src/Illuminate/Routing/Controller.php:54
#49 call_user_func_array in /var/www/print.internionline.it/vendor/laravel/framework/src/Illuminate/Routing/Controller.php:54
#48 Illuminate\Routing\Controller:callAction in /var/www/print.internionline.it/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php:45
#47 Illuminate\Routing\ControllerDispatcher:dispatch in /var/www/print.internionline.it/vendor/laravel/framework/src/Illuminate/Routing/Route.php:219
#46 Illuminate\Routing\Route:runController in /var/www/print.internionline.it/vendor/laravel/framework/src/Illuminate/Routing/Route.php:176
#45 Illuminate\Routing\Route:run in /var/www/print.internionline.it/vendor/laravel/framework/src/Illuminate/Routing/Router.php:680
#44 Illuminate\Routing\Router:Illuminate\Routing\{closure} in /var/www/print.internionline.it/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:30
#43 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /var/www/print.internionline.it/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php:41
#42 Illuminate\Routing\Middleware\SubstituteBindings:handle in /var/www/print.internionline.it/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:163
#41 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /var/www/print.internionline.it/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
#40 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /var/www/print.internionline.it/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php:75
#39 Illuminate\Foundation\Http\Middleware\VerifyCsrfToken:handle in /var/www/print.internionline.it/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:163
#38 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /var/www/print.internionline.it/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
#37 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /var/www/print.internionline.it/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php:49
#36 Illuminate\View\Middleware\ShareErrorsFromSession:handle in /var/www/print.internionline.it/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:163
#35 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /var/www/print.internionline.it/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
#34 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /var/www/print.internionline.it/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php:56
#33 Illuminate\Session\Middleware\StartSession:handle in /var/www/print.internionline.it/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:163
#32 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /var/www/print.internionline.it/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
#31 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /var/www/print.internionline.it/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php:37
#30 Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse:handle in /var/www/print.internionline.it/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:163
#29 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /var/www/print.internionline.it/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
#28 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /var/www/print.internionline.it/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php:66
#27 Illuminate\Cookie\Middleware\EncryptCookies:handle in /var/www/print.internionline.it/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:163
#26 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /var/www/print.internionline.it/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
#25 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /var/www/print.internionline.it/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:104
#24 Illuminate\Pipeline\Pipeline:then in /var/www/print.internionline.it/vendor/laravel/framework/src/Illuminate/Routing/Router.php:682
#23 Illuminate\Routing\Router:runRouteWithinStack in /var/www/print.internionline.it/vendor/laravel/framework/src/Illuminate/Routing/Router.php:657
#22 Illuminate\Routing\Router:runRoute in /var/www/print.internionline.it/vendor/laravel/framework/src/Illuminate/Routing/Router.php:623
#21 Illuminate\Routing\Router:dispatchToRoute in /var/www/print.internionline.it/vendor/laravel/framework/src/Illuminate/Routing/Router.php:612
#20 Illuminate\Routing\Router:dispatch in /var/www/print.internionline.it/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php:176
#19 Illuminate\Foundation\Http\Kernel:Illuminate\Foundation\Http\{closure} in /var/www/print.internionline.it/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:30
#18 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /var/www/print.internionline.it/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php:21
#17 Illuminate\Foundation\Http\Middleware\TransformsRequest:handle in /var/www/print.internionline.it/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:163
#16 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /var/www/print.internionline.it/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
#15 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /var/www/print.internionline.it/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php:21
#14 Illuminate\Foundation\Http\Middleware\TransformsRequest:handle in /var/www/print.internionline.it/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:163
#13 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /var/www/print.internionline.it/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
#12 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /var/www/print.internionline.it/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php:27
#11 Illuminate\Foundation\Http\Middleware\ValidatePostSize:handle in /var/www/print.internionline.it/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:163
#10 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /var/www/print.internionline.it/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
#9 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /var/www/print.internionline.it/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php:62
#8 Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode:handle in /var/www/print.internionline.it/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:163
#7 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /var/www/print.internionline.it/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
#6 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /var/www/print.internionline.it/vendor/fideloper/proxy/src/TrustProxies.php:57
#5 Fideloper\Proxy\TrustProxies:handle in /var/www/print.internionline.it/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:163
#4 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /var/www/print.internionline.it/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
#3 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /var/www/print.internionline.it/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:104
#2 Illuminate\Pipeline\Pipeline:then in /var/www/print.internionline.it/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php:151
#1 Illuminate\Foundation\Http\Kernel:sendRequestThroughRouter in /var/www/print.internionline.it/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php:116
#0 Illuminate\Foundation\Http\Kernel:handle in /var/www/print.internionline.it/public/index.php:55

**Comment by jorisatabix** [comment]
`composer require webklex/laravel-pdfmerger:1.0.3` in case you are waiting for the PR.

**Comment by jorisatabix** [comment]
@Webklex This can be closed since you've merged the PR. <3
