### ISSUE TITLE
Undefined index: heigth

### ISSUE THREAD

**Issue by laraben** [Webklex/laravel-pdfmerger#19]
I have a really weird issue.

The system was working fine until now...
The weirdest part is everything is working fine locally, but when i try on the production server i always get the error "Undefined index: height" from src/PDFMerger/PDFMerger.php:224

Its really driving me nuts.

Maybe you have an idea what could be the problem.

**Comment by Webklex** [comment]
Hi @laraben ,
have you checked / compared the php versions and the installed modules? Perhaps they are different?

Can you share the entire error stack? :)

Best regards,

**Comment by laraben** [comment]
Yes i have checked.
Production server : 
PHP 7.4.13
installed modules are the same versions
Composer is identical
Local : 
PHP 7.4.25

Exception (Only on production server):
Message
Undefined index: heigth
Level
ERROR
UserId
1
Exception
{
    "class": "ErrorException",
    "message": "Undefined index: heigth",
    "code": 0,
    "file": "/var/www/html/webapp/ascot/webappV2/vendor/webplex/laravel-pdfmerger/src/PDFMerger/PDFMerger.php:224",
    "trace": [
        "/var/www/html/webapp/ascot/webappV2/vendor/webplex/laravel-pdfmerger/src/PDFMerger/PDFMerger.php:224",
        "/var/www/html/webapp/ascot/webappV2/vendor/laravel/framework/src/Illuminate/Collections/Traits/EnumeratesValues.php:234",
        "/var/www/html/webapp/ascot/webappV2/vendor/webplex/laravel-pdfmerger/src/PDFMerger/PDFMerger.php:245",
        "/var/www/html/webapp/ascot/webappV2/vendor/webplex/laravel-pdfmerger/src/PDFMerger/PDFMerger.php:193",
        "/var/www/html/webapp/ascot/webappV2/app/Http/Controllers/DocsignController.php:219",
        "/var/www/html/webapp/ascot/webappV2/vendor/laravel/framework/src/Illuminate/Routing/Controller.php:54",
        "/var/www/html/webapp/ascot/webappV2/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php:45",
        "/var/www/html/webapp/ascot/webappV2/vendor/laravel/framework/src/Illuminate/Routing/Route.php:254",
        "/var/www/html/webapp/ascot/webappV2/vendor/laravel/framework/src/Illuminate/Routing/Route.php:197",
        "/var/www/html/webapp/ascot/webappV2/vendor/laravel/framework/src/Illuminate/Routing/Router.php:695",
        "/var/www/html/webapp/ascot/webappV2/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:128",
        "/var/www/html/webapp/ascot/webappV2/vendor/laravel/passport/src/Http/Middleware/CreateFreshApiToken.php:50",
        "/var/www/html/webapp/ascot/webappV2/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:167",
        "/var/www/html/webapp/ascot/webappV2/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php:50",
        "/var/www/html/webapp/ascot/webappV2/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:167",

**Comment by laraben** [comment]
I've found the issue.
But can't understand why.
I've dumped the size var to check its content , this was the dump : 
```
array:5 [
  "width" => 297.00008333333
  "height" => 210.00155555556
  0 => 297.00008333333
  1 => 210.00155555556
  "orientation" => "L"
]
```
for some reason it blocks on size["height"]

ive replaced size["width"] with size[0]
and size["height"] with size[1]

and now its working on the production server....
