### ISSUE TITLE
Target class [PDFMerger] does not exist.

### ISSUE THREAD

**Issue by yogeshGroony** [Webklex/laravel-pdfmerger#20]
exception: "Illuminate\\Contracts\\Container\\BindingResolutionException"
file: "C:\\xampp\\htdocs\\studiez_backend\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\Container.php"
line: 805
message: "Target class [PDFMerger] does not exist."

Code->
            $oMerger = PDFMerger::init(); 
            $oMerger->addPDF('bla.pdf');

**Comment by Webklex** [comment]
Hi @yogeshGroony ,
it seems like the facade alias isn't loaded. In that case you can call the class like this:
```php
use Webklex\PDFMerger\Facades\PDFMergerFacade as PDFMerger;

$oMerger = PDFMerger::init();
```

Best regards,

**Comment by yogeshGroony** [comment]
Resolved by "composer dump-autoload".
