### ISSUE TITLE
Compression technique not supported by the free parser shipped with FPDI

### ISSUE THREAD

**Issue by FarhanK501** [Webklex/laravel-pdfmerger#3]
Hi there,
Thank you so much for you work and awesome, easy to use library for laravel.
I've come across a situation where pdf version causing application to crash, I know I can do it in exception handling but the problem is I am not able to parse some pdf files which I think is version problem.
`Exception in pdf_parser.php line 126:This document (/xyz/pdffiles/xyz123.pdf) probably uses a compression technique which is not supported by the free parser shipped with FPDI. (See https://www.setasign.com/fpdi-pdf-parser for more details)`.

**Comment by Webklex** [comment]
Hi @FarhanK501 ,
thanks for your report. I'm glad you like my work :)

If I understand the problem correct it is actually caused by FPDI. So the only option to get around this bug would be to replace FPDI with something else. Do you know any free alternatives which don't have the same issue implemented?

Best regards

**Comment by FarhanK501** [comment]
Hi @Webklex ,

Sorry for the late update.
I've tried many free alternatives but there is something with pdf version 1.7 which is causing the issue.
The supported version in libraries were till 1.5 ~ 1.6.
So what I did was compiled PHP Imagick and parse the pdf.

Thank you so much for your work man.
You're awesome.

**Comment by wifirevaithi** [comment]
The issue will be resolved if i purchase the product ?

**Comment by larylinz** [comment]
how did you get on, wifirevaithi? I have an license, but do know, how to implemet it with this package.

**Comment by TimoKoerber** [comment]
> how did you get on, wifirevaithi? I have an license, but do know, how to implemet it with this package. 

@larylinz I want to the same thing. Did you find a solution for this?
