### ISSUE TITLE
Empty PDF after update to 1.3.1

### ISSUE THREAD

**Issue by KreutzerCode** [Webklex/laravel-pdfmerger#31]
Hello I have recently updated the laravel-pdfmerger from 1.3.0 to 1.3.1. 
Before the update, creating and downloading PDFS worked flawlessly. 
Since the update to version 1.3.1, all PDFs created with the pdfmerger were returned empty (0kb). 

![MicrosoftTeams-image](https://user-images.githubusercontent.com/53813841/195531082-ee1cbd94-8a1e-4110-be88-c14c444376ab.png)

So I looked at the changelog and I noticed that the download method was changed. When I rebuilt the method to the state of version 1.3.0, everything worked again without errors.

I can narrow down the problem to the now used response class does not work correctly (because it runs with the `oFPDI->Output()` method without errors).

from v1.3.0  (works flawlessly):

![MicrosoftTeams-image (3)](https://user-images.githubusercontent.com/53813841/195532625-5e827dca-a6f1-4bf0-934c-9344cf580082.png)

from v1.3.1  (outputs empty pdfs):

![MicrosoftTeams-image (4)](https://user-images.githubusercontent.com/53813841/195533041-dcb05d1d-f98f-4e0b-8db1-c281b3380032.png)

**Comment by wblondel** [comment]
I'm having the same issue, I would love to have your PR merged.

**Comment by wblondel** [comment]
Hi @Webklex , could you merge https://github.com/Webklex/laravel-pdfmerger/pull/32 so that this issue is fixed?

**Comment by KreutzerCode** [comment]
Fix is merged and included in release [1.3.2](https://github.com/Webklex/laravel-pdfmerger/releases/tag/1.3.2). Thanks @Webklex !

**Comment by henrik0804** [comment]
@KreutzerCode do you have a minimal working example on how to recreate this Bug on version 1.3.1? Upgrading to 1.3.2 broke using the download-Method in one of our Projects and I would like to look into where the differences are

**Comment by KreutzerCode** [comment]
Hi @henrik0804 , im sorry but its been 2 years since i encountered the bug and i cant provide you with an example. I just remember it like written in the issue - after upgrading version 1.3.0 to 1.3.1, the pdfs merged by this package came out empty in size and content. 

I tracked the problem to the that time "recently" changed Response behavior and wrote a fix for it in the PR #32 . Maybe you can start debugging this section in your project to get more information about what is going wrong in your project.
