### ISSUE TITLE
File not found. Even file exist in public directory of LARAVEL 10

### ISSUE THREAD

**Issue by Abdullah-Iftikhar** [Webklex/laravel-pdfmerger#44]
$pdfMerger = PDFMerger::init();
        $pdfMerger->addPDF($returnArr['contractData']->internalAgentContract->amlCourse->url, 'all');
        
   Showing This error. Even PDF exist locally.  How to resolve this issue. I have just follow the https://github.com/Webklex/laravel-pdfmerger steps.
        
![image](https://github.com/Webklex/laravel-pdfmerger/assets/53434692/81132bce-a161-440a-8686-343da7d8b1df)

**Comment by kroonal** [comment]
@Abdullah-Iftikhar please use path like **public_path($fileName)**
